
services:
  c2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
  web:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "8081:3000" 