
services:
  c2-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "8081:3000"