[package]
name = "stage-1"
version = "0.1.0"
edition = "2024"

[dependencies]

reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
